#!/usr/bin/env bash

set -e

# Get the absolute path of the directory containing this script
SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Get the absolute path of the root directory of the repository
ROOTDIR="$(cd "${SCRIPTDIR}/.." && pwd)"

set -x

# see also ".mailmap" for how email addresses and names are deduplicated
cat > "${ROOTDIR}/AUTHORS" <<- EOF
	# File @generated by hack/generate-authors.sh. DO NOT EDIT.
	# This file lists all contributors to the repository.
	# See hack/generate-authors.sh to make modifications.

	$(git -C "$ROOTDIR" log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf)
EOF

# Display a message indicating that the AUTHORS file has been generated
echo "AUTHORS file generated successfully at ${ROOTDIR}/AUTHORS"